from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict


class ToolCallResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    step: int
    tool_name: str
    input: dict
    output: str
    is_error: bool
    approval_status: str
    duration_ms: int


class DecisionRequest(BaseModel):
    # The id of the pending tool_calls ROW (not LangChain's string id): the decision names the exact
    # action the user was shown
    tool_call_id: int
    decision: Literal["approve", "reject"]


class PendingApproval(BaseModel):
    tool_call_id: int
    tool_name: str
    args: dict
    # Generated by code from the arguments, never written by the model
    summary: str
    expires_at: datetime
    expired: bool


class AgentRunResponse(BaseModel):
    # org_id and user_id are deliberately not included
    model_config = ConfigDict(from_attributes=True)

    id: int
    status: str
    step_count: int
    error: str | None
    started_at: datetime
    finished_at: datetime | None
    message_id: int
    answer_message_id: int | None
    # Oldest first
    tool_calls: list[ToolCallResponse]
    # Only while the status is waiting_approval
    pending_approval: PendingApproval | None = None
