"""create filings and ingestion_runs tables, add companies industry

Revision ID: 0f8ae16b3b79
Revises: ab4b8dd0de03
Create Date: 2026-10-02 04:27:14.566524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8ae16b3b79'
down_revision: Union[str, Sequence[str], None] = 'ab4b8dd0de03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed')", name='ck_ingestion_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=20), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('primary_document', sa.String(length=255), nullable=False),
    sa.Column('raw_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index('ix_filings_company_id_filed_on', 'filings', ['company_id', 'filed_on'], unique=False)
    op.add_column('companies', sa.Column('industry', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'industry')
    op.drop_index('ix_filings_company_id_filed_on', table_name='filings')
    op.drop_table('filings')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
