"""create financial_facts table

Revision ID: 15439b6dc2e2
Revises: 0f8ae16b3b79
Create Date: 2026-10-02 04:50:37.584936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15439b6dc2e2'
down_revision: Union[str, Sequence[str], None] = '0f8ae16b3b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=20), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'concept', 'unit', 'period_start', 'period_end', name='uq_financial_facts_period', postgresql_nulls_not_distinct=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_facts')
    # ### end Alembic commands ###
