"""create agent tables

Revision ID: 7e5f97537b7e
Revises: 61ca987c3964
Create Date: 2026-10-04 05:49:49.881771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5f97537b7e'
down_revision: Union[str, Sequence[str], None] = '61ca987c3964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('answer_message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('step_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'step_limit', 'timeout', 'cancelled')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['answer_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_org_id_user_id', 'agent_runs', ['org_id', 'user_id'], unique=False)
    op.create_index('ix_agent_runs_session_id', 'agent_runs', ['session_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('is_error', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approval_status', sa.String(length=20), server_default='not_required', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_status IN ('not_required', 'pending', 'approved', 'rejected')", name='ck_tool_calls_approval_status'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_run_id_id', 'tool_calls', ['run_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_run_id_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_agent_runs_session_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_org_id_user_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
