"""create watchlists tables

Revision ID: ab4b8dd0de03
Revises: bf7faefe32ae
Create Date: 2026-10-02 04:11:24.835231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4b8dd0de03'
down_revision: Union[str, Sequence[str], None] = 'bf7faefe32ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_org_id'), 'watchlists', ['org_id'], unique=False)
    op.create_index('uq_watchlists_org_id_lower_name', 'watchlists', ['org_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_index('uq_watchlists_org_id_lower_name', table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_org_id'), table_name='watchlists')
    op.drop_table('watchlists')
    # ### end Alembic commands ###
